---
- name: Install and Configure Jenkins
  hosts: jenkins_servers
  become: yes
  gather_facts: yes
  
  tasks:
    - name: Wait for SSH to be available
      wait_for_connection:
        delay: 5
        timeout: 300
    
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
          - git
          - wget
          - fontconfig
          - openjdk-17-jre
        state: present
    
    - name: Verify Java installation
      command: java -version
      register: java_version
      changed_when: false
    
    - name: Display Java version
      debug:
        msg: "{{ java_version.stderr_lines }}"
    
    - name: Add Jenkins GPG key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present
    
    - name: Add Jenkins repository
      apt_repository:
        repo: "deb https://pkg.jenkins.io/debian-stable binary/"
        state: present
        filename: jenkins
    
    - name: Update apt cache after adding Jenkins repo
      apt:
        update_cache: yes
    
    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
    
    - name: Ensure Jenkins service is started and enabled
      systemd:
        name: jenkins
        state: started
        enabled: yes
    
    - name: Wait for Jenkins to start up
      wait_for:
        host: 127.0.0.1
        port: 8080
        delay: 10
        timeout: 300
        state: started
    
    - name: Wait for Jenkins to be fully initialized
      uri:
        url: http://127.0.0.1:8080
        status_code: 200,403
        timeout: 5
      register: jenkins_service_status
      retries: 60
      delay: 5
      until: jenkins_service_status is succeeded
    
    - name: Check if initial admin password file exists
      stat:
        path: /var/lib/jenkins/secrets/initialAdminPassword
      register: admin_password_file
    
    - name: Read Jenkins initial admin password
      slurp:
        src: /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_initial_password
      when: admin_password_file.stat.exists
    
    - name: Display Jenkins initial admin password
      debug:
        msg: "Jenkins initial admin password: {{ jenkins_initial_password['content'] | b64decode | trim }}"
      when: admin_password_file.stat.exists
    
    - name: Save initial password to file for easy access
      copy:
        content: "{{ jenkins_initial_password['content'] | b64decode | trim }}"
        dest: /home/ubuntu/jenkins_initial_password.txt
        owner: ubuntu
        group: ubuntu
        mode: '0600'
      when: admin_password_file.stat.exists
    
    - name: Install Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    
    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
    
    - name: Update apt cache after adding Docker repo
      apt:
        update_cache: yes
    
    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
    
    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: yes
    
    - name: Add jenkins user to docker group
      user:
        name: jenkins
        groups: docker
        append: yes
    
    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
    
    - name: Restart Jenkins to apply docker group changes
      systemd:
        name: jenkins
        state: restarted
    
    - name: Wait for Jenkins to restart
      wait_for:
        host: 127.0.0.1
        port: 8080
        delay: 5
        timeout: 120
        state: started
    
    - name: Get Jenkins service status
      systemd:
        name: jenkins
      register: jenkins_status
    
    - name: Display Jenkins status
      debug:
        msg: "Jenkins is {{ jenkins_status.status.ActiveState }}"
    
    - name: Display Jenkins access information
      debug:
        msg:
          - "=========================================="
          - "Jenkins Installation Complete!"
          - "=========================================="
          - "Access Jenkins at: http://{{ ansible_default_ipv4.address }}:8080"
          - "Initial Admin Password: {{ jenkins_initial_password['content'] | b64decode | trim if admin_password_file.stat.exists else 'Already configured' }}"
          - "Password also saved in: /home/ubuntu/jenkins_initial_password.txt"
          - "=========================================="

