---
- name: Install Nginx and Docker
  hosts: web_servers
  become: yes
  gather_facts: yes
  
  tasks:
    - name: Wait for SSH to be available
      wait_for_connection:
        delay: 5
        timeout: 300
    
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
        state: present
    
    - name: Install Nginx
      apt:
        name: nginx
        state: present
    
    - name: Start and enable Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes
    
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    
    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
    
    - name: Update apt cache after adding Docker repo
      apt:
        update_cache: yes
    
    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
    
    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: yes
    
    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
    
    - name: Verify Nginx installation
      command: nginx -v
      register: nginx_version
      changed_when: false
    
    - name: Verify Docker installation
      command: docker --version
      register: docker_version
      changed_when: false
    
    - name: Display versions
      debug:
        msg:
          - "Nginx version: {{ nginx_version.stderr }}"
          - "Docker version: {{ docker_version.stdout }}"
    
    - name: Create backend directory
      file:
        path: /home/ubuntu/backend
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'
    
    - name: Copy backend files to server
      copy:
        src: "{{ playbook_dir }}/../backend/"
        dest: /home/ubuntu/backend/
        owner: ubuntu
        group: ubuntu
        mode: '0644'
    
    - name: Make backend directory executable
      file:
        path: /home/ubuntu/backend
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'
        recurse: yes
    
    - name: Stop existing backend container
      shell: docker compose down
      args:
        chdir: /home/ubuntu/backend
      ignore_errors: yes
      become: yes
    
    - name: Build and start backend with Docker Compose
      shell: docker compose up -d --build
      args:
        chdir: /home/ubuntu/backend
      become: yes
    
    - name: Wait for backend to be ready
      wait_for:
        port: 3000
        delay: 5
        timeout: 60
    
    - name: Configure Nginx as reverse proxy
      copy:
        dest: /etc/nginx/sites-available/backend
        content: |
          server {
              listen 80;
              server_name _;

              location / {
                  proxy_pass http://localhost:3000;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_cache_bypass $http_upgrade;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }
        owner: root
        group: root
        mode: '0644'
    
    - name: Remove default Nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
    
    - name: Enable backend site
      file:
        src: /etc/nginx/sites-available/backend
        dest: /etc/nginx/sites-enabled/backend
        state: link
    
    - name: Test Nginx configuration
      command: nginx -t
      register: nginx_test
      changed_when: false
    
    - name: Reload Nginx
      systemd:
        name: nginx
        state: reloaded
    
    - name: Verify backend is running
      uri:
        url: http://localhost:3000
        return_content: yes
      register: backend_test
    
    - name: Display backend response
      debug:
        msg: "Backend is running: {{ backend_test.json.message }}"
    
    - name: Test Nginx proxy
      uri:
        url: http://localhost
        return_content: yes
      register: proxy_test
    
    - name: Display proxy response
      debug:
        msg: "Nginx proxy is working: {{ proxy_test.json.message }}"

